# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

WorkItem.create([
{name: '爬虫類開店準備'},
{name: '爬虫類器水洗い'},
{name: '亀天日干し'},
{name: 'イグアナ天日干し'},
{name: 'ミーア出勤、ゲージ掃除'},
{name: 'ミーアゲージ水洗い'},
{name: 'ケープ出勤'},
{name: 'ケープゲージ水洗い'},
{name: 'ケープ展示場床材替え'},
{name: 'うさぎゲージ掃除、開店準備'},
{name: 'うさぎゲージ水洗い'},
{name: 'ぽん助掃除'},
{name: 'チンチラゲージ掃除'},
{name: 'デグー開店準備'},
{name: '猫出勤'},
{name: '猫トイレ掃除'},
{name: 'カワセミ日光浴、ゲージ掃除'},
{name: 'モルモット出勤、ゲージ掃除'},
{name: '小動物出勤'},
{name: 'ハムスター餌やり'},
{name: 'ハムスター床材替え'},
{name: 'ハムスター展示場床材替え'},
{name: 'ジャービル出勤'},
{name: 'ヤマネ出勤'},
{name: '掃除機がけ'},
{name: '猫部屋掃除機がけ'},
{name: 'モップがけ'},
{name: 'セラセット'},
{name: 'ゴミ袋セット'},
{name: '水ボトルセット'},
{name: 'おやつ作成'},
{name: 'うさぎ、モルモット餌水やり'},
{name: 'ハリネズミ掃除、餌水やり'},
{name: '猫ゲージ掃除、餌やり'},
{name: 'ミーアキャット餌やり'},
{name: 'ケープ餌水セッティング'},
{name: 'ヤマネ、ジャービル床材替え'},
{name: 'ヤマネ、ジャービル餌水セッティング'},
{name: 'ハムスター床材替え'},
{name: '雑巾干し'},
{name: 'フロア接客'},
{name: '受付'},
{name: '呼び込み'},
{name: '受付'},
{name: '昼休憩'},
{name: '呼び込み'},
{name: '受付'},
{name: 'フロア接客'},
{name: 'サバモニ餌やり'},
{name: '爬虫類虫餌やり'},
{name: '爬虫類餌準備'},
{name: 'デグー餌やり'},
{name: 'バロンゲージトイレ掃除'},
{name: 'ジャービル、ヤマネ帰宅'},
{name: 'うさぎ展示場掃除'},
{name: 'うさぎ移動'},
{name: 'ケープ帰宅、ガラス掃除'},
{name: 'ミーア帰宅、ガラス掃除'},
{name: 'ぽん助餌やり'},
{name: 'モルモット帰宅'},
{name: 'ゴミ収集、捨て'},
{name: 'フクロウ糞掃除'},
{name: '雑巾洗い'},
{name: '生体確認、ゲージ扉確認'},
])